package database

import (
	"strings"

	"github.com/midoriya/flashlearn-backend/internal/models"
)

type structuredExamBlueprint struct {
	ExamSet    string
	MockType   string
	SortBase   int
	BandTarget string
	Difficulty string

	WritingTopic string
	Task1Title   string
	Task1Prompt  string
	Task2Title   string
	Task2Prompt  string

	SpeakingTopic       string
	SpeakingPart1Title  string
	SpeakingPart1Prompt string
	SpeakingPart2Title  string
	SpeakingPart2Prompt string
	SpeakingPart2Cue    []string
	SpeakingPart3Title  string
	SpeakingPart3Prompt string

	ReadingTopic        string
	ReadingTitle        string
	ReadingPassage      string
	ReadingMCQPrompt    string
	ReadingMCQOptions   []string
	ReadingMCQAnswer    string
	ReadingTFPrompt     string
	ReadingTFAnswer     string
	ReadingMatchPrompt  string
	ReadingMatchOptions []string
	ReadingMatchAnswer  string

	ListeningTopic        string
	ListeningTitle        string
	ListeningScript       string
	ListeningBlankPrompt  string
	ListeningBlankAnswer  string
	ListeningMCQPrompt    string
	ListeningMCQOptions   []string
	ListeningMCQAnswer    string
	ListeningTFPrompt     string
	ListeningTFAnswer     string
}

func buildExpandedIELTSQuestionSeed() []models.IELTSQuestion {
	blueprints := buildExpandedCambridgeBlueprints()
	blueprints = append(blueprints, buildCambridgeExtraTestBlueprints()...)
	blueprints = append(blueprints, buildExpandedPredictionBlueprints()...)
	questions := make([]models.IELTSQuestion, 0, len(blueprints)*11)

	for _, blueprint := range blueprints {
		questions = append(questions, buildQuestionsFromBlueprint(blueprint)...)
	}

	return questions
}

func buildQuestionsFromBlueprint(blueprint structuredExamBlueprint) []models.IELTSQuestion {
	band := stringPtr(blueprint.BandTarget)
	writingGroup := blueprint.ExamSet + "-writing"
	speakingGroup := blueprint.ExamSet + "-speaking"
	readingGroup := blueprint.ExamSet + "-reading-1"
	listeningGroup := blueprint.ExamSet + "-listening-1"
	part2Cue := stringPtr(strings.Join(blueprint.SpeakingPart2Cue, "\n"))

	return []models.IELTSQuestion{
		{
			Section:       "writing",
			QuestionType:  "task1",
			Difficulty:    blueprint.Difficulty,
			MockType:      blueprint.MockType,
			Topic:         blueprint.WritingTopic,
			ExamSet:       blueprint.ExamSet,
			QuestionGroup: writingGroup,
			Title:         blueprint.Task1Title,
			Prompt:        blueprint.Task1Prompt,
			BandTarget:    band,
			SortOrder:     blueprint.SortBase + 1,
		},
		{
			Section:       "writing",
			QuestionType:  "task2",
			Difficulty:    blueprint.Difficulty,
			MockType:      blueprint.MockType,
			Topic:         blueprint.WritingTopic,
			ExamSet:       blueprint.ExamSet,
			QuestionGroup: writingGroup,
			Title:         blueprint.Task2Title,
			Prompt:        blueprint.Task2Prompt,
			BandTarget:    band,
			SortOrder:     blueprint.SortBase + 2,
		},
		{
			Section:       "speaking",
			QuestionType:  "part1",
			Difficulty:    "easy",
			MockType:      blueprint.MockType,
			Topic:         blueprint.SpeakingTopic,
			ExamSet:       blueprint.ExamSet,
			QuestionGroup: speakingGroup,
			Title:         blueprint.SpeakingPart1Title,
			Prompt:        blueprint.SpeakingPart1Prompt,
			BandTarget:    band,
			SortOrder:     blueprint.SortBase + 3,
		},
		{
			Section:       "speaking",
			QuestionType:  "part2",
			Difficulty:    "medium",
			MockType:      blueprint.MockType,
			Topic:         blueprint.SpeakingTopic,
			ExamSet:       blueprint.ExamSet,
			QuestionGroup: speakingGroup,
			Title:         blueprint.SpeakingPart2Title,
			Prompt:        blueprint.SpeakingPart2Prompt,
			Content:       part2Cue,
			BandTarget:    band,
			SortOrder:     blueprint.SortBase + 4,
		},
		{
			Section:       "speaking",
			QuestionType:  "part3",
			Difficulty:    blueprint.Difficulty,
			MockType:      blueprint.MockType,
			Topic:         blueprint.SpeakingTopic,
			ExamSet:       blueprint.ExamSet,
			QuestionGroup: speakingGroup,
			Title:         blueprint.SpeakingPart3Title,
			Prompt:        blueprint.SpeakingPart3Prompt,
			BandTarget:    band,
			SortOrder:     blueprint.SortBase + 5,
		},
		{
			Section:       "reading",
			QuestionType:  "multiple_choice",
			Difficulty:    blueprint.Difficulty,
			MockType:      blueprint.MockType,
			Topic:         blueprint.ReadingTopic,
			ExamSet:       blueprint.ExamSet,
			QuestionGroup: readingGroup,
			Title:         blueprint.ReadingTitle,
			Prompt:        blueprint.ReadingMCQPrompt,
			Content:       stringPtr(blueprint.ReadingPassage),
			Options:       jsonString(blueprint.ReadingMCQOptions),
			Answer:        stringPtr(blueprint.ReadingMCQAnswer),
			Explanation:   stringPtr("Use the passage details rather than background knowledge when choosing the answer."),
			BandTarget:    band,
			SortOrder:     blueprint.SortBase + 6,
		},
		{
			Section:       "reading",
			QuestionType:  "true_false",
			Difficulty:    blueprint.Difficulty,
			MockType:      blueprint.MockType,
			Topic:         blueprint.ReadingTopic,
			ExamSet:       blueprint.ExamSet,
			QuestionGroup: readingGroup,
			Title:         blueprint.ReadingTitle,
			Prompt:        blueprint.ReadingTFPrompt,
			Content:       stringPtr(blueprint.ReadingPassage),
			Answer:        stringPtr(blueprint.ReadingTFAnswer),
			Explanation:   stringPtr("Check whether the passage confirms or contradicts the statement directly."),
			BandTarget:    band,
			SortOrder:     blueprint.SortBase + 7,
		},
		{
			Section:       "reading",
			QuestionType:  "matching",
			Difficulty:    blueprint.Difficulty,
			MockType:      blueprint.MockType,
			Topic:         blueprint.ReadingTopic,
			ExamSet:       blueprint.ExamSet,
			QuestionGroup: readingGroup,
			Title:         blueprint.ReadingTitle,
			Prompt:        blueprint.ReadingMatchPrompt,
			Content:       stringPtr(blueprint.ReadingPassage),
			Options:       jsonString(blueprint.ReadingMatchOptions),
			Answer:        stringPtr(blueprint.ReadingMatchAnswer),
			Explanation:   stringPtr("Match the paraphrased idea to the supporting detail in the text."),
			BandTarget:    band,
			SortOrder:     blueprint.SortBase + 8,
		},
		{
			Section:       "listening",
			QuestionType:  "fill_blank",
			Difficulty:    "easy",
			MockType:      blueprint.MockType,
			Topic:         blueprint.ListeningTopic,
			ExamSet:       blueprint.ExamSet,
			QuestionGroup: listeningGroup,
			Title:         blueprint.ListeningTitle,
			Prompt:        blueprint.ListeningBlankPrompt,
			AudioScript:   stringPtr(blueprint.ListeningScript),
			Answer:        stringPtr(blueprint.ListeningBlankAnswer),
			Explanation:   stringPtr("Listen for the exact number, time, or phrase used by the speaker."),
			BandTarget:    band,
			SortOrder:     blueprint.SortBase + 9,
		},
		{
			Section:       "listening",
			QuestionType:  "multiple_choice",
			Difficulty:    blueprint.Difficulty,
			MockType:      blueprint.MockType,
			Topic:         blueprint.ListeningTopic,
			ExamSet:       blueprint.ExamSet,
			QuestionGroup: listeningGroup,
			Title:         blueprint.ListeningTitle,
			Prompt:        blueprint.ListeningMCQPrompt,
			AudioScript:   stringPtr(blueprint.ListeningScript),
			Options:       jsonString(blueprint.ListeningMCQOptions),
			Answer:        stringPtr(blueprint.ListeningMCQAnswer),
			Explanation:   stringPtr("Ignore early distractors and choose the final confirmed detail."),
			BandTarget:    band,
			SortOrder:     blueprint.SortBase + 10,
		},
		{
			Section:       "listening",
			QuestionType:  "true_false",
			Difficulty:    blueprint.Difficulty,
			MockType:      blueprint.MockType,
			Topic:         blueprint.ListeningTopic,
			ExamSet:       blueprint.ExamSet,
			QuestionGroup: listeningGroup,
			Title:         blueprint.ListeningTitle,
			Prompt:        blueprint.ListeningTFPrompt,
			AudioScript:   stringPtr(blueprint.ListeningScript),
			Answer:        stringPtr(blueprint.ListeningTFAnswer),
			Explanation:   stringPtr("Compare the statement with the final version of the information in the script."),
			BandTarget:    band,
			SortOrder:     blueprint.SortBase + 11,
		},
	}
}

func buildExpandedCambridgeBlueprints() []structuredExamBlueprint {
	return []structuredExamBlueprint{
		{
			ExamSet: "cambridge-10-test-1", MockType: "cambridge_style", SortBase: 4000, BandTarget: "6.5", Difficulty: "medium",
			WritingTopic: "Transport",
			Task1Title: "Cycle lanes and bus routes",
			Task1Prompt: "The map and table below show changes to cycle lanes and bus routes in a city centre between 2010 and 2025. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Remote work and cities",
			Task2Prompt: "Many people believe that remote work will make city centres less important in the future. To what extent do you agree or disagree?",
			SpeakingTopic: "City life",
			SpeakingPart1Title: "Commuting routines",
			SpeakingPart1Prompt: "How do you usually travel around your city, and why does that method suit you?",
			SpeakingPart2Title: "A journey you remember",
			SpeakingPart2Prompt: "Describe a journey in your city that you remember well.",
			SpeakingPart2Cue: []string{"where you went", "who you were with", "what happened during the journey", "and explain why you still remember it"},
			SpeakingPart3Title: "Future transport",
			SpeakingPart3Prompt: "What changes should cities make if they want people to rely less on private cars?",
			ReadingTopic: "Environment",
			ReadingTitle: "Cooling streets with shade",
			ReadingPassage: "Several city councils have begun redesigning busy streets with more shade trees and lighter building materials. Planners report that shaded streets stay cooler in the afternoon and attract more pedestrians. However, the projects only succeed when maintenance budgets remain in place after the first year.",
			ReadingMCQPrompt: "According to the passage, what helps shaded street projects remain successful?",
			ReadingMCQOptions: []string{"More advertising campaigns", "Long-term maintenance funding", "Closing streets to pedestrians", "Replacing trees every summer"},
			ReadingMCQAnswer: "Long-term maintenance funding",
			ReadingTFPrompt: "The passage says shaded streets can encourage more people to walk there.",
			ReadingTFAnswer: "true",
			ReadingMatchPrompt: "Match the idea 'lower afternoon temperatures' to the correct benefit.",
			ReadingMatchOptions: []string{"A. streets stay cooler", "B. councils spend less in winter", "C. drivers travel faster"},
			ReadingMatchAnswer: "A. streets stay cooler",
			ListeningTopic: "Travel",
			ListeningTitle: "Weekend rail pass",
			ListeningScript: "Agent: The weekend rail pass now costs forty-two pounds and covers travel from Friday evening until Sunday night. Student: Does that include the airport line? Agent: Yes, but seat reservations on airport trains must be booked online before noon on Friday. Student: So the app is only for reservations? Agent: Exactly.",
			ListeningBlankPrompt: "The weekend rail pass costs £______.",
			ListeningBlankAnswer: "42",
			ListeningMCQPrompt: "What must be booked online?",
			ListeningMCQOptions: []string{"The pass itself", "Seat reservations on airport trains", "All return tickets", "A station locker"},
			ListeningMCQAnswer: "Seat reservations on airport trains",
			ListeningTFPrompt: "The speaker says the rail pass is valid only on Saturday and Sunday.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "cambridge-11-test-1", MockType: "cambridge_style", SortBase: 4100, BandTarget: "6.5", Difficulty: "medium",
			WritingTopic: "Culture",
			Task1Title: "Museum attendance",
			Task1Prompt: "The charts below compare museum attendance by age group and time of day in one city over a six-month period. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Preserving local history",
			Task2Prompt: "Some people think local history should be taught through museums and field trips rather than in classrooms. Discuss both views and give your own opinion.",
			SpeakingTopic: "Culture",
			SpeakingPart1Title: "Museums",
			SpeakingPart1Prompt: "Do you enjoy visiting museums, and what usually makes a museum interesting for you?",
			SpeakingPart2Title: "A place that teaches you something",
			SpeakingPart2Prompt: "Describe a place you visited where you learned something new.",
			SpeakingPart2Cue: []string{"where the place was", "what you learned there", "who you went with", "and explain why the experience stayed in your mind"},
			SpeakingPart3Title: "Local heritage",
			SpeakingPart3Prompt: "Why do some communities find it difficult to preserve local heritage sites?",
			ReadingTopic: "History",
			ReadingTitle: "Community archive projects",
			ReadingPassage: "Community archive projects often begin with volunteers collecting photographs and oral histories from long-term residents. The most effective projects then organise the material into searchable themes so schools and local groups can reuse it. Without clear cataloguing, valuable stories are often stored but rarely used.",
			ReadingMCQPrompt: "What makes community archive projects especially effective?",
			ReadingMCQOptions: []string{"Charging visitors an entry fee", "Turning materials into searchable themes", "Limiting access to teachers only", "Focusing only on very old photographs"},
			ReadingMCQAnswer: "Turning materials into searchable themes",
			ReadingTFPrompt: "The passage says stories may remain unused when archive material is poorly organised.",
			ReadingTFAnswer: "true",
			ReadingMatchPrompt: "Match the phrase 'searchable themes' to the most suitable outcome.",
			ReadingMatchOptions: []string{"A. easier reuse by schools", "B. fewer volunteers needed", "C. longer interviews"},
			ReadingMatchAnswer: "A. easier reuse by schools",
			ListeningTopic: "Culture",
			ListeningTitle: "Heritage walking tour",
			ListeningScript: "Guide: Please arrive at the visitor centre by 10.20 because the walking tour begins at half past ten exactly. We will start in the old market square before moving to the riverside warehouse district. The final stop is a restored cinema where you can collect the printed map of the route.",
			ListeningBlankPrompt: "The tour begins at ______.",
			ListeningBlankAnswer: "10.30",
			ListeningMCQPrompt: "Where is the first stop on the walking tour?",
			ListeningMCQOptions: []string{"The visitor centre", "The restored cinema", "The old market square", "The warehouse district"},
			ListeningMCQAnswer: "The old market square",
			ListeningTFPrompt: "Participants collect the printed map at the start of the tour.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "cambridge-12-test-1", MockType: "cambridge_style", SortBase: 4200, BandTarget: "7.0", Difficulty: "hard",
			WritingTopic: "Education",
			Task1Title: "School device access",
			Task1Prompt: "The table and bar chart below show the percentage of students with access to tablets at school and at home in four regions between 2016 and 2026. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Digital and printed resources",
			Task2Prompt: "In schools, digital resources are becoming more common than printed books. Do the advantages of this trend outweigh the disadvantages?",
			SpeakingTopic: "Study",
			SpeakingPart1Title: "Learning tools",
			SpeakingPart1Prompt: "What kind of tools or apps do you use when you study, and why?",
			SpeakingPart2Title: "A skill you learned efficiently",
			SpeakingPart2Prompt: "Describe a skill you learned more quickly than you expected.",
			SpeakingPart2Cue: []string{"what the skill was", "how you learned it", "why the process was effective", "and explain how you felt after learning it"},
			SpeakingPart3Title: "Technology in education",
			SpeakingPart3Prompt: "How can schools use technology well without making learning too passive?",
			ReadingTopic: "Study",
			ReadingTitle: "Quiet spaces for concentration",
			ReadingPassage: "Researchers comparing study environments found that students concentrated for longer in quiet shared spaces than in noisy social areas. The key factor was not complete silence but predictable sound levels. When noise changed suddenly, concentration dropped even among experienced learners.",
			ReadingMCQPrompt: "What most reduced concentration in the study?",
			ReadingMCQOptions: []string{"Working in silence", "Studying with experienced learners", "Sudden changes in noise", "Shared study areas"},
			ReadingMCQAnswer: "Sudden changes in noise",
			ReadingTFPrompt: "The passage says predictable sound levels can still support concentration.",
			ReadingTFAnswer: "true",
			ReadingMatchPrompt: "Match the idea 'quiet shared spaces' to the result reported by researchers.",
			ReadingMatchOptions: []string{"A. longer concentration", "B. more social interaction", "C. shorter revision sessions"},
			ReadingMatchAnswer: "A. longer concentration",
			ListeningTopic: "Education",
			ListeningTitle: "University skills workshop",
			ListeningScript: "Tutor: The academic skills workshop starts at 1.15 in Room 6B. We begin with note-making, then move on to summarising sources, and we finish with a short session on presentation openings. You do not need to print anything because the worksheet will be shared by email afterwards.",
			ListeningBlankPrompt: "The workshop starts at ______.",
			ListeningBlankAnswer: "1.15",
			ListeningMCQPrompt: "What is covered at the end of the workshop?",
			ListeningMCQOptions: []string{"Note-making", "Presentation openings", "Source referencing only", "Printing guidelines"},
			ListeningMCQAnswer: "Presentation openings",
			ListeningTFPrompt: "Students are told to bring printed worksheets to the workshop.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "cambridge-13-test-1", MockType: "cambridge_style", SortBase: 4300, BandTarget: "6.5", Difficulty: "medium",
			WritingTopic: "Housing",
			Task1Title: "Apartment size and rent",
			Task1Prompt: "The charts below show average apartment size and monthly rent in five districts in 2015 and 2025. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Housing priorities",
			Task2Prompt: "Some people believe that affordable housing is more important than preserving the original character of older neighbourhoods. Discuss both views and give your own opinion.",
			SpeakingTopic: "Home",
			SpeakingPart1Title: "Where you live",
			SpeakingPart1Prompt: "What do you like most about the place where you live now?",
			SpeakingPart2Title: "A home you liked visiting",
			SpeakingPart2Prompt: "Describe a home you visited that you liked very much.",
			SpeakingPart2Cue: []string{"whose home it was", "what it looked like", "what made it comfortable", "and explain why it impressed you"},
			SpeakingPart3Title: "Urban housing choices",
			SpeakingPart3Prompt: "Why do housing choices often become more difficult in fast-growing cities?",
			ReadingTopic: "Cities",
			ReadingTitle: "Shared courtyards in apartment blocks",
			ReadingPassage: "Architects working on dense housing projects increasingly include shared courtyards between apartment buildings. These spaces are designed to improve natural light, create informal meeting points, and provide a small sense of openness for residents. The strongest results appear when management rules are simple and residents feel invited to use the area regularly.",
			ReadingMCQPrompt: "What is one stated purpose of shared courtyards?",
			ReadingMCQOptions: []string{"To increase parking space", "To improve natural light", "To replace indoor corridors", "To reduce rent costs"},
			ReadingMCQAnswer: "To improve natural light",
			ReadingTFPrompt: "The passage suggests complex rules make shared courtyards more successful.",
			ReadingTFAnswer: "false",
			ReadingMatchPrompt: "Match the idea 'informal meeting points' to the main social effect.",
			ReadingMatchOptions: []string{"A. residents meet more naturally", "B. buildings become taller", "C. rent becomes fixed"},
			ReadingMatchAnswer: "A. residents meet more naturally",
			ListeningTopic: "Accommodation",
			ListeningTitle: "Tenant orientation",
			ListeningScript: "Manager: Welcome to Riverside Apartments. The shared laundry room is on the second floor and opens at 6 a.m. each day. If you want to reserve the meeting room, send a request through the tenant portal at least twenty-four hours in advance. Recycling bins are kept beside the west entrance, not in the basement.",
			ListeningBlankPrompt: "The laundry room opens at ______ each day.",
			ListeningBlankAnswer: "6 a.m.",
			ListeningMCQPrompt: "How should tenants reserve the meeting room?",
			ListeningMCQOptions: []string{"By asking the caretaker in person", "By calling reception", "Through the tenant portal", "By leaving a note in the lobby"},
			ListeningMCQAnswer: "Through the tenant portal",
			ListeningTFPrompt: "Recycling bins are stored in the basement.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "cambridge-14-test-1", MockType: "cambridge_style", SortBase: 4400, BandTarget: "7.0", Difficulty: "hard",
			WritingTopic: "Environment",
			Task1Title: "Water recycling process",
			Task1Prompt: "The diagram below shows the stages used to recycle grey water for use in public buildings. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Environmental responsibility",
			Task2Prompt: "Some people think individuals cannot do much to improve the environment, while others believe personal actions still matter. Discuss both views and give your own opinion.",
			SpeakingTopic: "Environment",
			SpeakingPart1Title: "Saving water",
			SpeakingPart1Prompt: "Do you ever think about how much water you use each day? Why or why not?",
			SpeakingPart2Title: "A positive environmental action",
			SpeakingPart2Prompt: "Describe something you did that was good for the environment.",
			SpeakingPart2Cue: []string{"what you did", "when you decided to do it", "whether it was difficult", "and explain why you felt it was worthwhile"},
			SpeakingPart3Title: "Shared environmental duties",
			SpeakingPart3Prompt: "Should environmental solutions focus more on governments or on ordinary citizens? Why?",
			ReadingTopic: "Environment",
			ReadingTitle: "Water-sensitive campuses",
			ReadingPassage: "Universities in dry regions have begun redesigning campuses to capture rainwater from roofs and slow down runoff across paths and gardens. These systems reduce pressure on public supplies and also create useful outdoor learning spaces. Designers warn, however, that the systems fail when maintenance teams are not trained properly.",
			ReadingMCQPrompt: "What additional benefit of water-sensitive campus design is mentioned?",
			ReadingMCQOptions: []string{"Cheaper tuition fees", "Outdoor learning spaces", "More car parking", "Longer academic terms"},
			ReadingMCQAnswer: "Outdoor learning spaces",
			ReadingTFPrompt: "The passage states that poor staff training can weaken the system.",
			ReadingTFAnswer: "true",
			ReadingMatchPrompt: "Match the phrase 'capture rainwater from roofs' to its direct purpose.",
			ReadingMatchOptions: []string{"A. reduce pressure on public supplies", "B. increase campus traffic", "C. shorten maintenance schedules"},
			ReadingMatchAnswer: "A. reduce pressure on public supplies",
			ListeningTopic: "Environment",
			ListeningTitle: "Community water workshop",
			ListeningScript: "Presenter: The community workshop on household water saving starts at 11.40 in Hall C. The first session explains low-cost bathroom changes, the second compares garden watering methods, and the final demonstration shows how to check for hidden pipe leaks. Handouts will be uploaded after the event.",
			ListeningBlankPrompt: "The workshop starts at ______.",
			ListeningBlankAnswer: "11.40",
			ListeningMCQPrompt: "What is shown in the final demonstration?",
			ListeningMCQOptions: []string{"Bathroom design plans", "How to check for hidden leaks", "How to build new pipes", "How to repaint a hall"},
			ListeningMCQAnswer: "How to check for hidden leaks",
			ListeningTFPrompt: "Printed handouts are given to everyone before the workshop begins.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "cambridge-15-test-1", MockType: "cambridge_style", SortBase: 4500, BandTarget: "6.5", Difficulty: "medium",
			WritingTopic: "Work",
			Task1Title: "Office attendance patterns",
			Task1Prompt: "The line graph below shows average weekly office attendance in three industries between 2018 and 2026. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Work-life balance",
			Task2Prompt: "Employers should offer shorter working weeks even if this means lower productivity in some industries. To what extent do you agree or disagree?",
			SpeakingTopic: "Work",
			SpeakingPart1Title: "Work preferences",
			SpeakingPart1Prompt: "Would you prefer a highly structured job or a flexible one? Why?",
			SpeakingPart2Title: "A good team experience",
			SpeakingPart2Prompt: "Describe a time when you worked well with other people.",
			SpeakingPart2Cue: []string{"what you were doing", "who you worked with", "what made the teamwork effective", "and explain what you learned from the experience"},
			SpeakingPart3Title: "Changes at work",
			SpeakingPart3Prompt: "How do you think workplaces will change if flexible schedules become more common?",
			ReadingTopic: "Work",
			ReadingTitle: "Four-day trials",
			ReadingPassage: "Companies testing four-day work weeks often report better morale and lower staff turnover. The strongest gains appear when managers redesign meetings and handovers instead of simply compressing the same workload into fewer days. Businesses that ignore workflow changes usually see weaker results.",
			ReadingMCQPrompt: "What is linked to the strongest gains in four-day trials?",
			ReadingMCQOptions: []string{"Hiring more staff immediately", "Redesigning meetings and handovers", "Increasing customer opening hours", "Extending the working day"},
			ReadingMCQAnswer: "Redesigning meetings and handovers",
			ReadingTFPrompt: "The passage says lower staff turnover can follow four-day work week trials.",
			ReadingTFAnswer: "true",
			ReadingMatchPrompt: "Match the phrase 'ignore workflow changes' to the likely outcome.",
			ReadingMatchOptions: []string{"A. weaker results", "B. higher morale", "C. faster recruitment"},
			ReadingMatchAnswer: "A. weaker results",
			ListeningTopic: "Work",
			ListeningTitle: "Project handover briefing",
			ListeningScript: "Supervisor: Monday's handover meeting now starts at 8.45 instead of nine. Please upload your progress summary before breakfast because the design team will read it in advance. We also moved the client review from Wednesday to Thursday so the finance notes can be added first.",
			ListeningBlankPrompt: "The handover meeting begins at ______.",
			ListeningBlankAnswer: "8.45",
			ListeningMCQPrompt: "Why was the client review moved to Thursday?",
			ListeningMCQOptions: []string{"To shorten the meeting", "To add finance notes first", "To include breakfast", "To wait for a new designer"},
			ListeningMCQAnswer: "To add finance notes first",
			ListeningTFPrompt: "The design team reads the progress summary only during the meeting.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "cambridge-16-test-1", MockType: "cambridge_style", SortBase: 4600, BandTarget: "7.0", Difficulty: "hard",
			WritingTopic: "Tourism",
			Task1Title: "Seasonal visitor numbers",
			Task1Prompt: "The graph and table below show seasonal visitor numbers and average visitor spending in a coastal town from 2014 to 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Tourism management",
			Task2Prompt: "Tourist destinations should limit visitor numbers in peak season even if local businesses earn less money. Discuss both views and give your own opinion.",
			SpeakingTopic: "Travel",
			SpeakingPart1Title: "Tourist places",
			SpeakingPart1Prompt: "Do you like visiting places that are popular with tourists? Why or why not?",
			SpeakingPart2Title: "A place that was crowded",
			SpeakingPart2Prompt: "Describe a place you visited that was very crowded.",
			SpeakingPart2Cue: []string{"where it was", "why there were many people there", "how you felt about the situation", "and explain whether you would go there again"},
			SpeakingPart3Title: "Balancing tourism",
			SpeakingPart3Prompt: "How can local areas benefit from tourism without damaging everyday life for residents?",
			ReadingTopic: "Travel",
			ReadingTitle: "Managing fragile coastlines",
			ReadingPassage: "Protected coastal areas often attract more visitors after they are promoted online, but managers increasingly use timed entry systems to prevent overcrowding. These systems protect walking routes and wildlife habitats while still allowing tourism income to continue. Their success depends on visitors understanding why limits exist.",
			ReadingMCQPrompt: "Why do managers use timed entry systems?",
			ReadingMCQOptions: []string{"To raise ticket prices", "To prevent overcrowding", "To reduce wildlife surveys", "To close online promotion"},
			ReadingMCQAnswer: "To prevent overcrowding",
			ReadingTFPrompt: "The passage suggests visitor understanding is important for the system to work well.",
			ReadingTFAnswer: "true",
			ReadingMatchPrompt: "Match the phrase 'timed entry systems' to the correct effect.",
			ReadingMatchOptions: []string{"A. protect routes and habitats", "B. shorten tourist seasons", "C. remove all tourism income"},
			ReadingMatchAnswer: "A. protect routes and habitats",
			ListeningTopic: "Tourism",
			ListeningTitle: "Coastal visitor centre",
			ListeningScript: "Officer: The guided cliff walk leaves at 2.05 from the visitor centre entrance. Remember that the upper path is closed this week, so the group will use the lower trail by the old lighthouse. If you need waterproof jackets, they can be borrowed beside the ticket desk before departure.",
			ListeningBlankPrompt: "The guided walk leaves at ______.",
			ListeningBlankAnswer: "2.05",
			ListeningMCQPrompt: "Which route will the group use?",
			ListeningMCQOptions: []string{"The upper path", "The lower trail by the lighthouse", "The harbour road", "The forest path"},
			ListeningMCQAnswer: "The lower trail by the lighthouse",
			ListeningTFPrompt: "Waterproof jackets are collected after the walk.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "cambridge-18-test-1", MockType: "cambridge_style", SortBase: 4700, BandTarget: "6.5", Difficulty: "medium",
			WritingTopic: "Community",
			Task1Title: "Recycling participation",
			Task1Prompt: "The charts below show participation in three recycling schemes in four neighbourhoods in 2012 and 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Volunteering among young people",
			Task2Prompt: "Schools should require all teenagers to complete a period of community volunteering. To what extent do you agree or disagree?",
			SpeakingTopic: "Community",
			SpeakingPart1Title: "Helping others",
			SpeakingPart1Prompt: "Do you often help people in your neighbourhood? Why or why not?",
			SpeakingPart2Title: "A time you helped",
			SpeakingPart2Prompt: "Describe a time when you helped someone in your community.",
			SpeakingPart2Cue: []string{"who you helped", "what you did", "how the person responded", "and explain what you learned from the experience"},
			SpeakingPart3Title: "Volunteering habits",
			SpeakingPart3Prompt: "Why do some people volunteer regularly while others rarely do so?",
			ReadingTopic: "Society",
			ReadingTitle: "Repair and reuse groups",
			ReadingPassage: "Local repair groups have grown quickly because they reduce waste and give residents practical support. Organisers say the biggest long-term benefit is that members become more confident about fixing common problems themselves. The groups work best when volunteers teach simple methods instead of doing all the work for participants.",
			ReadingMCQPrompt: "What is described as the biggest long-term benefit of repair groups?",
			ReadingMCQOptions: []string{"Cheaper new products", "Greater confidence in solving problems", "Fewer public libraries", "Faster online shopping"},
			ReadingMCQAnswer: "Greater confidence in solving problems",
			ReadingTFPrompt: "The passage says repair groups are most effective when volunteers only fix items themselves.",
			ReadingTFAnswer: "false",
			ReadingMatchPrompt: "Match the phrase 'teach simple methods' to the related outcome.",
			ReadingMatchOptions: []string{"A. participants become more independent", "B. groups close sooner", "C. fewer items are brought in"},
			ReadingMatchAnswer: "A. participants become more independent",
			ListeningTopic: "Community",
			ListeningTitle: "Volunteer training session",
			ListeningScript: "Coordinator: The volunteer training session starts at 5.25 in the sports hall office. First we explain the event map, then we practise greeting visitors, and finally we review the emergency phone list. Everyone should collect a blue badge from the registration table before the talk begins.",
			ListeningBlankPrompt: "The training session starts at ______.",
			ListeningBlankAnswer: "5.25",
			ListeningMCQPrompt: "What should volunteers collect before the talk?",
			ListeningMCQOptions: []string{"A printed map", "A blue badge", "A meal ticket", "A key card"},
			ListeningMCQAnswer: "A blue badge",
			ListeningTFPrompt: "Emergency procedures are discussed before the event map.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "cambridge-19-test-1", MockType: "cambridge_style", SortBase: 4800, BandTarget: "7.0", Difficulty: "hard",
			WritingTopic: "Energy",
			Task1Title: "Household energy mix",
			Task1Prompt: "The charts below show changes in household energy use from four sources between 2005 and 2025 in one country. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Energy demand and behaviour",
			Task2Prompt: "The most effective way to reduce energy demand is to change household behaviour rather than improve technology. Discuss both views and give your own opinion.",
			SpeakingTopic: "Technology",
			SpeakingPart1Title: "Using energy carefully",
			SpeakingPart1Prompt: "Do you think much about saving electricity at home? Why or why not?",
			SpeakingPart2Title: "A useful device",
			SpeakingPart2Prompt: "Describe a device that helps you save time or energy.",
			SpeakingPart2Cue: []string{"what the device is", "how often you use it", "why it is useful", "and explain whether you would recommend it"},
			SpeakingPart3Title: "Technology and energy use",
			SpeakingPart3Prompt: "Do new technologies always reduce energy use, or can they sometimes increase it?",
			ReadingTopic: "Technology",
			ReadingTitle: "Smart grids at neighbourhood scale",
			ReadingPassage: "Neighbourhood smart grids combine data from homes, batteries, and local solar panels so electricity can be balanced more efficiently. Engineers note that the greatest savings appear when households also receive clear feedback about peak hours. Without understandable information, many residents do not change their behaviour enough to support the system.",
			ReadingMCQPrompt: "According to the passage, what helps smart grids achieve the greatest savings?",
			ReadingMCQOptions: []string{"Larger batteries only", "Clear feedback about peak hours", "Fewer solar panels", "Longer billing cycles"},
			ReadingMCQAnswer: "Clear feedback about peak hours",
			ReadingTFPrompt: "The passage says all residents naturally adapt their behaviour without guidance.",
			ReadingTFAnswer: "false",
			ReadingMatchPrompt: "Match the phrase 'understandable information' to the reason it matters.",
			ReadingMatchOptions: []string{"A. residents change behaviour more effectively", "B. electricity becomes free", "C. solar panels last longer"},
			ReadingMatchAnswer: "A. residents change behaviour more effectively",
			ListeningTopic: "Energy",
			ListeningTitle: "Home energy advice line",
			ListeningScript: "Advisor: Your home visit is booked for 3.35 next Tuesday. The assessor will first check loft insulation, then test the heating controls, and finally review your electricity bills from the last six months. Please leave a recent bill on the kitchen table before the visit.",
			ListeningBlankPrompt: "The home visit is booked for ______.",
			ListeningBlankAnswer: "3.35",
			ListeningMCQPrompt: "What should be left on the kitchen table?",
			ListeningMCQOptions: []string{"A house key", "A recent electricity bill", "A bus ticket", "A copy of the booking form"},
			ListeningMCQAnswer: "A recent electricity bill",
			ListeningTFPrompt: "The heating controls are checked before the loft insulation.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "cambridge-20-test-1", MockType: "cambridge_style", SortBase: 4900, BandTarget: "7.0", Difficulty: "hard",
			WritingTopic: "Society",
			Task1Title: "Services for older residents",
			Task1Prompt: "The charts below compare the use of four community services by older residents in 2010 and 2030. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Ageing population support",
			Task2Prompt: "As populations grow older, governments should spend more on community care than on hospital expansion. To what extent do you agree or disagree?",
			SpeakingTopic: "Society",
			SpeakingPart1Title: "Different age groups",
			SpeakingPart1Prompt: "Do you spend much time with people from older generations? Why or why not?",
			SpeakingPart2Title: "An older person you respect",
			SpeakingPart2Prompt: "Describe an older person you respect.",
			SpeakingPart2Cue: []string{"who the person is", "how you know them", "what qualities you admire", "and explain what you have learned from them"},
			SpeakingPart3Title: "Support for ageing societies",
			SpeakingPart3Prompt: "What changes should societies make if they want older people to remain active and independent?",
			ReadingTopic: "Society",
			ReadingTitle: "Age-friendly neighbourhood design",
			ReadingPassage: "Age-friendly neighbourhood design usually focuses on walkable streets, clear public information, and services located close to daily needs. Researchers argue that these features benefit not only older residents but also parents with children and people recovering from illness. The largest barrier is often poor coordination between transport planners and health services.",
			ReadingMCQPrompt: "What is described as the largest barrier to age-friendly neighbourhood design?",
			ReadingMCQOptions: []string{"A lack of public interest", "Poor coordination between sectors", "Too many local services", "Shorter walking routes"},
			ReadingMCQAnswer: "Poor coordination between sectors",
			ReadingTFPrompt: "The passage says age-friendly design can help more than one group in society.",
			ReadingTFAnswer: "true",
			ReadingMatchPrompt: "Match the phrase 'services close to daily needs' to the practical benefit.",
			ReadingMatchOptions: []string{"A. easier everyday independence", "B. fewer libraries", "C. longer commutes"},
			ReadingMatchAnswer: "A. easier everyday independence",
			ListeningTopic: "Society",
			ListeningTitle: "Community care briefing",
			ListeningScript: "Manager: The community care briefing begins at 9.50 in Meeting Room B. We start with transport assistance, then review home meal delivery, and finish by explaining the weekly social clubs for older residents. Volunteers should sign in beside the reception phone before entering the room.",
			ListeningBlankPrompt: "The briefing begins at ______.",
			ListeningBlankAnswer: "9.50",
			ListeningMCQPrompt: "What is discussed at the end of the briefing?",
			ListeningMCQOptions: []string{"Transport assistance", "Weekly social clubs", "Recruitment interviews", "Phone maintenance"},
			ListeningMCQAnswer: "Weekly social clubs",
			ListeningTFPrompt: "Volunteers sign in after the briefing has ended.",
			ListeningTFAnswer: "false",
		},
	}
}

func buildExpandedPredictionBlueprints() []structuredExamBlueprint {
	return []structuredExamBlueprint{
		{
			ExamSet: "predictions-2026-set-1", MockType: "predictions", SortBase: 5000, BandTarget: "6.5", Difficulty: "medium",
			WritingTopic: "Cities",
			Task1Title: "Climate-ready public spaces",
			Task1Prompt: "The plans below show how a city square was redesigned to cope with hotter summers between 2022 and 2026. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Heat adaptation in cities",
			Task2Prompt: "Cities should spend more on making public spaces comfortable in extreme weather than on building new entertainment facilities. To what extent do you agree or disagree?",
			SpeakingTopic: "Cities",
			SpeakingPart1Title: "Outdoor spaces",
			SpeakingPart1Prompt: "Do you enjoy spending time in outdoor public spaces? Why or why not?",
			SpeakingPart2Title: "A public space you like",
			SpeakingPart2Prompt: "Describe a public space that you enjoy spending time in.",
			SpeakingPart2Cue: []string{"where it is", "what people do there", "when you go there", "and explain why it suits you"},
			SpeakingPart3Title: "Climate-ready design",
			SpeakingPart3Prompt: "How should cities redesign public areas as weather becomes more extreme?",
			ReadingTopic: "Cities",
			ReadingTitle: "Cooling urban plazas",
			ReadingPassage: "Urban designers are testing shaded seating, water-saving planting, and reflective paving in busy public plazas. These features lower surface temperatures and help the area remain usable during heat waves. The most successful projects combine design changes with clear maintenance plans from the start.",
			ReadingMCQPrompt: "What is a shared feature of the most successful plaza projects?",
			ReadingMCQOptions: []string{"Private parking spaces", "Clear maintenance plans", "Underground shopping malls", "Longer opening hours"},
			ReadingMCQAnswer: "Clear maintenance plans",
			ReadingTFPrompt: "The passage says reflective paving can help reduce surface temperature.",
			ReadingTFAnswer: "true",
			ReadingMatchPrompt: "Match the phrase 'water-saving planting' to the design goal.",
			ReadingMatchOptions: []string{"A. keep spaces usable in heat", "B. increase traffic speed", "C. remove public seating"},
			ReadingMatchAnswer: "A. keep spaces usable in heat",
			ListeningTopic: "Cities",
			ListeningTitle: "Park redesign briefing",
			ListeningScript: "Planner: The community briefing starts at 6.10 in the library hall. We will first explain the new shade structures, then the water refill points, and finally the evening lighting plan for summer events. Feedback forms should be handed to the assistant beside the main entrance before you leave.",
			ListeningBlankPrompt: "The community briefing starts at ______.",
			ListeningBlankAnswer: "6.10",
			ListeningMCQPrompt: "What is explained second in the briefing?",
			ListeningMCQOptions: []string{"Evening lighting", "Water refill points", "Tree removal", "Sports bookings"},
			ListeningMCQAnswer: "Water refill points",
			ListeningTFPrompt: "People submit feedback forms at the beginning of the event.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "predictions-2026-set-2", MockType: "predictions", SortBase: 5100, BandTarget: "6.5", Difficulty: "medium",
			WritingTopic: "Technology",
			Task1Title: "Study assistant usage",
			Task1Prompt: "The charts below compare how often students used four kinds of digital study assistants in 2021 and 2026. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "AI study tools",
			Task2Prompt: "Students should be encouraged to use AI study assistants, provided they explain how the tool supported their work. Discuss both views and give your own opinion.",
			SpeakingTopic: "Technology",
			SpeakingPart1Title: "Study apps",
			SpeakingPart1Prompt: "Do you use apps or websites when you study? Why or why not?",
			SpeakingPart2Title: "A digital tool you use well",
			SpeakingPart2Prompt: "Describe a digital tool that helps you study or work effectively.",
			SpeakingPart2Cue: []string{"what the tool is", "how you use it", "what makes it effective", "and explain whether you would recommend it"},
			SpeakingPart3Title: "Responsible AI use",
			SpeakingPart3Prompt: "How can schools make sure students use AI tools responsibly rather than depend on them too much?",
			ReadingTopic: "Technology",
			ReadingTitle: "Feedback dashboards for learners",
			ReadingPassage: "Learning platforms now offer dashboards that show students how often they review material and where they make repeated mistakes. Teachers say these dashboards are most useful when students discuss the patterns with a person rather than simply checking scores alone. Numbers without reflection can easily be misunderstood.",
			ReadingMCQPrompt: "What makes feedback dashboards most useful according to teachers?",
			ReadingMCQOptions: []string{"Higher subscription fees", "Discussion with a real person", "Longer screen time", "Removing all scores"},
			ReadingMCQAnswer: "Discussion with a real person",
			ReadingTFPrompt: "The passage suggests numbers can be misunderstood without reflection.",
			ReadingTFAnswer: "true",
			ReadingMatchPrompt: "Match the phrase 'repeated mistakes' to the benefit of a dashboard.",
			ReadingMatchOptions: []string{"A. shows patterns learners should address", "B. replaces teachers completely", "C. shortens exams"},
			ReadingMatchAnswer: "A. shows patterns learners should address",
			ListeningTopic: "Technology",
			ListeningTitle: "Digital study lab induction",
			ListeningScript: "Trainer: The induction begins at 4.20 in Lab 3. We start with account setup, then move to the practice feedback dashboard, and end with a short explanation of how to export revision notes. Please bring your student card because you'll need it to activate the printer balance.",
			ListeningBlankPrompt: "The induction begins at ______.",
			ListeningBlankAnswer: "4.20",
			ListeningMCQPrompt: "What is covered in the middle part of the induction?",
			ListeningMCQOptions: []string{"Printer balance", "The feedback dashboard", "Exporting certificates", "Loaning laptops"},
			ListeningMCQAnswer: "The feedback dashboard",
			ListeningTFPrompt: "Students do not need their student card for the induction.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "predictions-2026-set-3", MockType: "predictions", SortBase: 5200, BandTarget: "7.0", Difficulty: "hard",
			WritingTopic: "Work",
			Task1Title: "Freelance and full-time employment",
			Task1Prompt: "The graph below shows the proportion of workers in freelance and full-time employment in three industries from 2015 to 2027. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Flexible career paths",
			Task2Prompt: "People should expect to change careers several times during their working lives rather than stay in one profession. To what extent do you agree or disagree?",
			SpeakingTopic: "Work",
			SpeakingPart1Title: "Career plans",
			SpeakingPart1Prompt: "Do you prefer long-term plans for your career or a more flexible approach? Why?",
			SpeakingPart2Title: "A career decision",
			SpeakingPart2Prompt: "Describe an important career or study decision you made.",
			SpeakingPart2Cue: []string{"what the decision was", "what choices you had", "why you chose that option", "and explain how you felt afterwards"},
			SpeakingPart3Title: "Changing professions",
			SpeakingPart3Prompt: "Why do some people now expect to change profession more often than in the past?",
			ReadingTopic: "Work",
			ReadingTitle: "Portfolio careers",
			ReadingPassage: "Portfolio careers combine several part-time roles or projects rather than one permanent job. Supporters say they offer variety and resilience when one source of income becomes unstable. Critics point out that success depends on strong planning skills and a willingness to manage uncertainty.",
			ReadingMCQPrompt: "What benefit of portfolio careers is mentioned in the passage?",
			ReadingMCQOptions: []string{"Guaranteed promotion", "Resilience when one income source weakens", "Fixed working hours", "No need for planning"},
			ReadingMCQAnswer: "Resilience when one income source weakens",
			ReadingTFPrompt: "The passage says portfolio careers suit people who dislike uncertainty.",
			ReadingTFAnswer: "false",
			ReadingMatchPrompt: "Match the phrase 'strong planning skills' to why they matter.",
			ReadingMatchOptions: []string{"A. managing multiple roles", "B. reducing holiday time", "C. avoiding all taxes"},
			ReadingMatchAnswer: "A. managing multiple roles",
			ListeningTopic: "Work",
			ListeningTitle: "Freelancer onboarding call",
			ListeningScript: "Coordinator: Your onboarding call starts at 2.25 on Thursday. We'll begin with contract access, then cover invoicing dates, and finally explain how project feedback is shared through the client portal. Please upload your bank form before Wednesday evening so payment is not delayed.",
			ListeningBlankPrompt: "The onboarding call starts at ______.",
			ListeningBlankAnswer: "2.25",
			ListeningMCQPrompt: "What is discussed at the end of the call?",
			ListeningMCQOptions: []string{"Contract access", "Bank forms", "How feedback is shared", "Holiday requests"},
			ListeningMCQAnswer: "How feedback is shared",
			ListeningTFPrompt: "The bank form can be uploaded after Wednesday evening without affecting payment.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "predictions-2026-set-4", MockType: "predictions", SortBase: 5300, BandTarget: "6.5", Difficulty: "medium",
			WritingTopic: "Food",
			Task1Title: "Food delivery routes",
			Task1Prompt: "The maps below show how food delivery routes in a town changed after a low-emission zone was introduced. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Sustainable food choices",
			Task2Prompt: "Consumers should pay more for food that is produced sustainably, even if cheaper alternatives are available. To what extent do you agree or disagree?",
			SpeakingTopic: "Food",
			SpeakingPart1Title: "Meals",
			SpeakingPart1Prompt: "Do you prefer cooking your own meals or ordering food? Why?",
			SpeakingPart2Title: "A meal you remember",
			SpeakingPart2Prompt: "Describe a meal you had that you still remember well.",
			SpeakingPart2Cue: []string{"what the meal was", "where you had it", "who you were with", "and explain why it remains memorable"},
			SpeakingPart3Title: "Food systems",
			SpeakingPart3Prompt: "How can societies encourage people to choose more sustainable food without forcing them?",
			ReadingTopic: "Food",
			ReadingTitle: "Local supply chains",
			ReadingPassage: "Shorter food supply chains reduce travel distance and can help smaller producers sell directly to customers. Yet researchers note that short distance alone does not guarantee sustainability because storage, packaging, and seasonal growing conditions also matter. The most useful comparisons examine the whole chain instead of one factor.",
			ReadingMCQPrompt: "Why is short distance alone not enough to judge sustainability?",
			ReadingMCQOptions: []string{"Because transport never matters", "Because other parts of the chain also affect impact", "Because local producers avoid packaging", "Because customers ignore price"},
			ReadingMCQAnswer: "Because other parts of the chain also affect impact",
			ReadingTFPrompt: "The passage recommends examining the whole supply chain when making comparisons.",
			ReadingTFAnswer: "true",
			ReadingMatchPrompt: "Match the phrase 'whole chain' to the reason it is useful.",
			ReadingMatchOptions: []string{"A. it gives a fairer comparison", "B. it reduces farming seasons", "C. it removes customer demand"},
			ReadingMatchAnswer: "A. it gives a fairer comparison",
			ListeningTopic: "Food",
			ListeningTitle: "Farm market planning call",
			ListeningScript: "Organiser: The planning call begins at 7.15 on Monday evening. We will first confirm stall numbers, then discuss waste reduction rules, and finally decide where the shared cold-storage van should park. Please email your product list before lunchtime on Monday.",
			ListeningBlankPrompt: "The planning call begins at ______.",
			ListeningBlankAnswer: "7.15",
			ListeningMCQPrompt: "What is discussed last in the call?",
			ListeningMCQOptions: []string{"Stall numbers", "Waste rules", "Where the cold-storage van should park", "Ticket prices"},
			ListeningMCQAnswer: "Where the cold-storage van should park",
			ListeningTFPrompt: "Sellers can send their product list after the call finishes.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "predictions-2026-set-5", MockType: "predictions", SortBase: 5400, BandTarget: "7.0", Difficulty: "hard",
			WritingTopic: "Technology",
			Task1Title: "Privacy settings usage",
			Task1Prompt: "The table below shows the percentage of users who changed five privacy settings on social platforms in 2018 and 2026. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Digital privacy responsibility",
			Task2Prompt: "Technology companies should be more responsible than users for protecting online privacy. Discuss both views and give your own opinion.",
			SpeakingTopic: "Technology",
			SpeakingPart1Title: "Online habits",
			SpeakingPart1Prompt: "Do you usually think carefully before sharing information online? Why or why not?",
			SpeakingPart2Title: "A time you were careful online",
			SpeakingPart2Prompt: "Describe a time when you were careful about sharing information online.",
			SpeakingPart2Cue: []string{"what situation it was", "what decision you made", "why you were cautious", "and explain whether you think you made the right choice"},
			SpeakingPart3Title: "Privacy and convenience",
			SpeakingPart3Prompt: "Why do people often accept less privacy in exchange for convenience online?",
			ReadingTopic: "Technology",
			ReadingTitle: "Digital consent design",
			ReadingPassage: "Digital consent systems are easier to trust when they explain choices clearly and avoid hiding key settings behind complex menus. Researchers argue that users make better decisions when the consequences of sharing are explained in simple language. Confusing design can create the appearance of choice without genuine control.",
			ReadingMCQPrompt: "What helps users make better privacy decisions?",
			ReadingMCQOptions: []string{"Long legal documents", "Simple explanations of consequences", "More hidden settings", "Automatic public sharing"},
			ReadingMCQAnswer: "Simple explanations of consequences",
			ReadingTFPrompt: "The passage suggests confusing design can reduce genuine user control.",
			ReadingTFAnswer: "true",
			ReadingMatchPrompt: "Match the phrase 'appearance of choice' to the implied problem.",
			ReadingMatchOptions: []string{"A. users seem free but are not well informed", "B. companies lose all data", "C. passwords become shorter"},
			ReadingMatchAnswer: "A. users seem free but are not well informed",
			ListeningTopic: "Technology",
			ListeningTitle: "App privacy workshop",
			ListeningScript: "Speaker: The privacy workshop starts at 5.05 in Seminar Room 2. We begin with permission settings, then compare tracking options, and end with advice on stronger account recovery methods. If you want the checklist, scan the code on the final slide before the session closes.",
			ListeningBlankPrompt: "The privacy workshop starts at ______.",
			ListeningBlankAnswer: "5.05",
			ListeningMCQPrompt: "What is covered at the end of the workshop?",
			ListeningMCQOptions: []string{"Permission settings", "Tracking options", "Account recovery methods", "How to repair phones"},
			ListeningMCQAnswer: "Account recovery methods",
			ListeningTFPrompt: "The checklist is handed out on paper before the workshop begins.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "predictions-2026-set-6", MockType: "predictions", SortBase: 5500, BandTarget: "6.5", Difficulty: "medium",
			WritingTopic: "Transport",
			Task1Title: "Bus priority lanes",
			Task1Prompt: "The maps below show how bus priority lanes and interchange points were added to a suburban corridor between 2019 and 2025. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Public transport funding",
			Task2Prompt: "Governments should spend more on reliable public transport than on building new roads for private cars. To what extent do you agree or disagree?",
			SpeakingTopic: "Transport",
			SpeakingPart1Title: "Travel choices",
			SpeakingPart1Prompt: "What affects your choice of transport most: price, speed, or comfort?",
			SpeakingPart2Title: "A useful transport improvement",
			SpeakingPart2Prompt: "Describe a transport improvement that would help people where you live.",
			SpeakingPart2Cue: []string{"what the improvement is", "who would benefit most", "how it would change daily travel", "and explain why it matters"},
			SpeakingPart3Title: "Transport priorities",
			SpeakingPart3Prompt: "Why is it sometimes difficult for governments to persuade people to use public transport more often?",
			ReadingTopic: "Transport",
			ReadingTitle: "Reliable bus networks",
			ReadingPassage: "Passengers are more likely to return to bus networks when services become reliable rather than simply more frequent on paper. Transport researchers note that accurate real-time information and easy transfers reduce uncertainty for users. When journeys feel unpredictable, even cheaper tickets may not attract regular passengers.",
			ReadingMCQPrompt: "What reduces uncertainty for users according to the passage?",
			ReadingMCQOptions: []string{"Cheaper tickets alone", "Accurate real-time information and easy transfers", "Fewer route options", "Longer bus stops"},
			ReadingMCQAnswer: "Accurate real-time information and easy transfers",
			ReadingTFPrompt: "The passage says lower ticket prices always guarantee regular passengers.",
			ReadingTFAnswer: "false",
			ReadingMatchPrompt: "Match the phrase 'journeys feel unpredictable' to the likely passenger response.",
			ReadingMatchOptions: []string{"A. they avoid using the service regularly", "B. they travel more often", "C. they stop checking real-time information"},
			ReadingMatchAnswer: "A. they avoid using the service regularly",
			ListeningTopic: "Transport",
			ListeningTitle: "Interchange station announcement",
			ListeningScript: "Announcer: The transport consultation opens at 1.40 in the upper waiting hall. Officers will first present the new bus priority lanes, then explain the transfer ticket system, and finally answer questions about the proposed park-and-ride site. Feedback cards should be placed in the blue box by the escalator.",
			ListeningBlankPrompt: "The consultation opens at ______.",
			ListeningBlankAnswer: "1.40",
			ListeningMCQPrompt: "What is explained second in the session?",
			ListeningMCQOptions: []string{"Bus priority lanes", "The transfer ticket system", "The park-and-ride site", "Escalator safety"},
			ListeningMCQAnswer: "The transfer ticket system",
			ListeningTFPrompt: "Feedback cards are collected near the escalator.",
			ListeningTFAnswer: "true",
		},
		{
			ExamSet: "predictions-2026-set-7", MockType: "predictions", SortBase: 5600, BandTarget: "7.0", Difficulty: "hard",
			WritingTopic: "Health",
			Task1Title: "Remote health appointments",
			Task1Prompt: "The charts below compare the percentage of routine medical appointments completed online and in person in four age groups between 2020 and 2026. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Remote healthcare",
			Task2Prompt: "Remote medical consultations should become a standard option in public healthcare systems. Discuss both views and give your own opinion.",
			SpeakingTopic: "Health",
			SpeakingPart1Title: "Healthcare access",
			SpeakingPart1Prompt: "Do you think it is easy to get basic healthcare advice where you live? Why or why not?",
			SpeakingPart2Title: "Useful advice you received",
			SpeakingPart2Prompt: "Describe a piece of health advice that was useful for you.",
			SpeakingPart2Cue: []string{"what the advice was", "who gave it to you", "why it was useful", "and explain whether you followed it for a long time"},
			SpeakingPart3Title: "Digital healthcare",
			SpeakingPart3Prompt: "What are the main advantages and risks of using remote consultations more widely?",
			ReadingTopic: "Health",
			ReadingTitle: "Monitoring long-term conditions remotely",
			ReadingPassage: "Remote monitoring tools allow patients with long-term conditions to send simple health data to clinics without travelling each week. Doctors say the approach works best when unusual readings trigger quick follow-up from a real professional. Technology on its own cannot replace trust and explanation during treatment.",
			ReadingMCQPrompt: "When does remote monitoring work best according to doctors?",
			ReadingMCQOptions: []string{"When patients receive quick follow-up on unusual readings", "When clinics stop in-person care entirely", "When devices replace all explanations", "When data is sent once a year"},
			ReadingMCQAnswer: "When patients receive quick follow-up on unusual readings",
			ReadingTFPrompt: "The passage states that technology alone can replace trust in treatment.",
			ReadingTFAnswer: "false",
			ReadingMatchPrompt: "Match the phrase 'quick follow-up' to why it matters.",
			ReadingMatchOptions: []string{"A. it keeps remote care meaningful", "B. it reduces all clinic costs to zero", "C. it removes the need for doctors"},
			ReadingMatchAnswer: "A. it keeps remote care meaningful",
			ListeningTopic: "Health",
			ListeningTitle: "Clinic app introduction",
			ListeningScript: "Nurse: The clinic app session starts at 10.45 in Conference Room 1. We will first show how to book repeat prescriptions, then explain how to upload blood pressure readings, and finally discuss when patients should still request a face-to-face appointment. Please bring your phone charger in case your battery runs low.",
			ListeningBlankPrompt: "The app session starts at ______.",
			ListeningBlankAnswer: "10.45",
			ListeningMCQPrompt: "What is explained after repeat prescriptions?",
			ListeningMCQOptions: []string{"How to upload blood pressure readings", "How to buy a new phone", "How to cancel all appointments", "How to print parking permits"},
			ListeningMCQAnswer: "How to upload blood pressure readings",
			ListeningTFPrompt: "Patients are told that face-to-face appointments are never necessary anymore.",
			ListeningTFAnswer: "false",
		},
		{
			ExamSet: "predictions-2026-set-8", MockType: "predictions", SortBase: 5700, BandTarget: "6.5", Difficulty: "medium",
			WritingTopic: "Economy",
			Task1Title: "Creative industry employment",
			Task1Prompt: "The graph below shows employment in four creative industries in one region from 2016 to 2026. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
			Task2Title: "Support for creative workers",
			Task2Prompt: "Governments should invest more in the creative industries because they contribute to both the economy and public well-being. To what extent do you agree or disagree?",
			SpeakingTopic: "Culture",
			SpeakingPart1Title: "Creative hobbies",
			SpeakingPart1Prompt: "Do you enjoy any creative hobbies, or would you like to try one in the future?",
			SpeakingPart2Title: "A creative person you admire",
			SpeakingPart2Prompt: "Describe a creative person whose work you admire.",
			SpeakingPart2Cue: []string{"who the person is", "what kind of work they do", "how you found out about them", "and explain why you admire them"},
			SpeakingPart3Title: "Creative industries",
			SpeakingPart3Prompt: "Why do some societies value creative industries more than others?",
			ReadingTopic: "Culture",
			ReadingTitle: "Creative districts and small businesses",
			ReadingPassage: "Creative districts often grow when affordable workspace, public events, and local networks develop together. Economists note that small creative businesses need visibility as much as low rent, because audiences and collaborators are essential in the early stages. Districts that focus only on branding without supporting real activity usually fade quickly.",
			ReadingMCQPrompt: "What do small creative businesses need as much as low rent?",
			ReadingMCQOptions: []string{"Visibility", "Longer tax forms", "Fewer collaborators", "Permanent sponsorship"},
			ReadingMCQAnswer: "Visibility",
			ReadingTFPrompt: "The passage says branding alone is usually enough to build a lasting creative district.",
			ReadingTFAnswer: "false",
			ReadingMatchPrompt: "Match the phrase 'real activity' to what it includes.",
			ReadingMatchOptions: []string{"A. audiences and collaborators", "B. empty buildings", "C. fewer public events"},
			ReadingMatchAnswer: "A. audiences and collaborators",
			ListeningTopic: "Culture",
			ListeningTitle: "Arts incubator orientation",
			ListeningScript: "Host: The arts incubator orientation begins at 12.35 in Studio 4. We start with workspace rules, then explain the shared promotion calendar, and finally outline the small grant scheme for first-time exhibitors. Please sign the attendance sheet before taking a welcome pack from the side table.",
			ListeningBlankPrompt: "The orientation begins at ______.",
			ListeningBlankAnswer: "12.35",
			ListeningMCQPrompt: "What is explained after the workspace rules?",
			ListeningMCQOptions: []string{"The small grant scheme", "The shared promotion calendar", "The welcome pack design", "The building sale"},
			ListeningMCQAnswer: "The shared promotion calendar",
			ListeningTFPrompt: "People collect a welcome pack before signing the attendance sheet.",
			ListeningTFAnswer: "false",
		},
	}
}
