package database

import (
	"github.com/midoriya/flashlearn-backend/internal/models"
)

// buildMockTests returns IELTSMaterial entries for all mock/practice test files.
func buildMockTests() []models.IELTSMaterial {
	s := 5000
	next := func() int { v := s; s++; return v }

	return []models.IELTSMaterial{

		// ── CAMBRIDGE IELTS OFFICIAL ───────────────────────────────────────

		{
			Title:       "Cambridge IELTS 3 (Academic)",
			Description: "Official Cambridge past papers — 4 complete Academic tests with answer keys and model answers.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/104_Cambridge IELTS ACADEMIC 3.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 5 (Academic)",
			Description: "Official Cambridge past papers — 4 complete Academic tests with answer keys and model answers.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/102_Cambridge IELTS ACADEMIC 5.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 6 (Academic) — Part 2",
			Description: "Official Cambridge past papers — Academic tests from volume 6.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/100_Cambridge IELTS ACADEMIC 6-2part.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 7",
			Description: "Official Cambridge past papers — 4 complete tests with answer keys, model answers, and examiner commentary.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/85_Cambridge ielts 7.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 8",
			Description: "Official Cambridge past papers — 4 complete tests for all 4 skills.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/75_Cambridge IELTS 8.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 9",
			Description: "Official Cambridge past papers — 4 Academic tests with answer keys.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/82_Cambridge IELTS 9.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 10",
			Description: "Official Cambridge past papers — 4 complete Academic tests.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/80_Cambridge IELTS 10.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 11 (Clear PDF)",
			Description: "Official Cambridge past papers — 4 complete Academic tests, clear scan version.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/76_Cambridge IELTS 11 - Clear PDF Version.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 12",
			Description: "Official Cambridge past papers — 4 complete Academic tests with updated question types.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/79_Cambridge IELTS 12 PDF.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 13",
			Description: "Official Cambridge past papers — 4 Academic tests reflecting modern exam format.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/77_IELTS Cambridge 13.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 14",
			Description: "Official Cambridge past papers — 4 complete Academic tests.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/81_IELTS Cambridge IELTS 14.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 15",
			Description: "Official Cambridge past papers — 4 complete Academic tests.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/78_s cambridge_ielts_15.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 15.2",
			Description: "Additional Cambridge IELTS 15 practice tests.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/724_Cambridge IELTS 15.2.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 16 (Academic)",
			Description: "Official Cambridge past papers — 4 Academic tests with the most recent exam format.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/83_x Cambridge IELTS 16 Academic.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 18",
			Description: "Official Cambridge past papers — latest volume with 4 complete tests.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/606_Cambridge_IELTS_18_L_cambridge_library.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Cambridge IELTS 20",
			Description: "The newest Cambridge IELTS volume — 4 complete tests reflecting the current exam.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/3110_CAMBRIDGE IELTS 20 (@REALEXAMIELTS).pdf",
			SortOrder:   next(),
		},

		// ── TRAINERS & EXAM BANKS ─────────────────────────────────────────

		{
			Title:       "IELTS Trainer — 6 Practice Tests",
			Description: "Cambridge IELTS Trainer with 6 full practice tests and detailed skill-building activities.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/374_IELTS-Trainer.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Trainer 2",
			Description: "Cambridge IELTS Trainer 2 with additional practice tests and updated exam content.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/3350_IELTS_Trainer_2.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Barron's IELTS Practice Exams",
			Description: "Full-length IELTS practice exams with answer explanations and scoring guide.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/84_barrons_ielts_practice_exams.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Barron's IELTS 2016 (4th Edition)",
			Description: "Comprehensive Barron's IELTS guide with multiple practice tests and strategies.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/601_1608297442Barron's IELTS_2016, 4th -528p-.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Practice Tests with Explanatory Key",
			Description: "Complete practice test collection with detailed answer explanations for every question.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/129_pdfcoffee_com_ielts_practice_tests_with_explanatory_key_pdf_free.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Tests — Set 1",
			Description: "Collection of IELTS practice tests covering all four skills.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/130_IELTS_tests.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Tests — Set 2",
			Description: "Additional IELTS practice test set for comprehensive exam preparation.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/44_IELTS_tests.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "General Training — Practice Tests",
			Description: "IELTS General Training module practice tests with answer keys.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/610_General Training - Practice tests.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Reading Test — General Training",
			Description: "General Training reading practice test.",
			Category:    "reading",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/115_IELTS Reading Test (General Training).pdf",
			SortOrder:   next(),
		},

		// ── IELTS SPECIAL JOURNALS ────────────────────────────────────────

		{
			Title:       "IELTS Special Journal 1",
			Description: "IELTS Special Journal volume 1 — curated practice material and exam strategies.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/267_IELTS Special Journal 1 - Standard (2).pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Special Journal 2",
			Description: "IELTS Special Journal volume 2.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/268_IELTS Special Journal 2 - Standard (1).pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Special Journal 3",
			Description: "IELTS Special Journal volume 3.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/269_IELTS Special Journal 3 - Standard.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Special Journal 4",
			Description: "IELTS Special Journal volume 4.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/270_IELTS Special Journal 4 - Standard.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Special Journal 5",
			Description: "IELTS Special Journal volume 5.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/271_IELTS Special Journal 5 - Standard.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Special Journal 6",
			Description: "IELTS Special Journal volume 6.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/272_IELTS Special Journal 6 - Standard.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Special Journal 7",
			Description: "IELTS Special Journal volume 7.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/273_IELTS Special Journal 7 - Standard.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Special Journal 8",
			Description: "IELTS Special Journal volume 8.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/274_IELTS Special Journal 8 - Standard.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Special Journal 9",
			Description: "IELTS Special Journal volume 9.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/275_IELTS Special Journal 9 - Standard.pdf",
			SortOrder:   next(),
		},

		// ── ACTUAL EXAM PAPERS ────────────────────────────────────────────

		{
			Title:       "Actual Tests — Academic Reading (Oct–Jan 2021–2022)",
			Description: "Real IELTS Academic Reading papers from October 2021 to January 2022 exam sessions.",
			Category:    "reading",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/101_IELTS Actual Reading Oct-Jan 2021 2022.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Actual Tests — Academic Reading (Jun–Sep 2021)",
			Description: "Real IELTS Academic Reading papers from June to September 2021 sessions.",
			Category:    "reading",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/95_Actual Tests Academic Reading Jun-Sep 2021.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Actual Tests — Speaking (Oct–Jan 2021–2022)",
			Description: "Real IELTS Speaking questions from October 2021 to January 2022 exam sessions.",
			Category:    "speaking",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/103_IELTS Actual Speaking Oct-Jan 2021 2022.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Actual Tests — Speaking (Oct–Jan 2022)",
			Description: "Real IELTS Speaking questions from October to January 2022.",
			Category:    "speaking",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/73_IELTS Speaking Actual Test Oct to January 2022.pdf",
			SortOrder:   next(),
		},

		// ── PREDICTION SETS ───────────────────────────────────────────────

		{
			Title:       "2024 Real Exam Questions (@johnnys_IELTS)",
			Description: "Compilation of actual 2024 IELTS exam questions collected by Johnny's IELTS community.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/533_2024 REAL EXAM QUESTIONS @johnnys_IELTS.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Dr. Chung — 63 Tips & 16 Tests",
			Description: "16 complete practice tests plus 63 expert tips for IELTS preparation.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/1345_Dr.Chung-63tips-16Tests.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Writing Review — November 2019",
			Description: "Post-exam analysis of November 2019 Writing questions with model answers.",
			Category:    "writing",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/276_IELTS Writing Review Nov 2019.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Vietnam Writing Predictions 2025",
			Description: "IELTS Writing predictions for 2025 based on Vietnam exam centre trends.",
			Category:    "writing",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/2255_VIETNAM WRITING 2025.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Practice Test 1",
			Description: "Full IELTS practice test #1.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/1343_Practice Test 1.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Practice Test 2",
			Description: "Full IELTS practice test #2.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/1342_Practice Test 2.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Practice Test 3",
			Description: "Full IELTS practice test #3.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/1341_Practice Test 3.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Practice Test 4",
			Description: "Full IELTS practice test #4.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/1340_Practice Test 4.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Practice Test 5",
			Description: "Full IELTS practice test #5.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/1339_Practice Test 5.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Reading Practice 1",
			Description: "IELTS Reading practice passage set #1.",
			Category:    "reading",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/117_Reading 1.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Reading Practice 2",
			Description: "IELTS Reading practice passage set #2.",
			Category:    "reading",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/118_Reading 2.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Master IELTS Writing Band 9.0 Essays",
			Description: "Collection of Band 9.0 model essays for Writing Task 2 with detailed analysis.",
			Category:    "writing",
			Type:        "mock_test",
			Difficulty:  "advanced",
			FilePath:    "telegram-media/1460_Master IELTS Writing Band 9.0 Essays.pdf",
			SortOrder:   next(),
		},
		{
			Title:       "The 20-Day IELTS Essay Challenge",
			Description: "20 essay prompts with model answers — one per day to build writing stamina.",
			Category:    "writing",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/494_The 20 day IELTS essay challenge. (@PDF_IELTS).pdf",
			SortOrder:   next(),
		},
		{
			Title:       "IELTS Model Essays",
			Description: "Collection of model essays for Task 2 across various topics.",
			Category:    "writing",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/495_IELTS Model Essays (@PDF_IELTS).pdf",
			SortOrder:   next(),
		},
		{
			Title:       "230 IELTS Writing Samples",
			Description: "230 model writing samples covering Task 1 and Task 2 at various band levels.",
			Category:    "writing",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/2133_230 IELTS Writing Samples (Munan Shaik) (z-lib.org).pdf",
			SortOrder:   next(),
		},
		{
			Title:       "Complete IELTS Bands 6.5–7.5",
			Description: "Cambridge Complete IELTS targeting Band 6.5–7.5 with integrated practice tests.",
			Category:    "general",
			Type:        "mock_test",
			Difficulty:  "intermediate",
			FilePath:    "telegram-media/88_Complete_IELTS_Bands_6_5-7_5.pdf",
			SortOrder:   next(),
		},
	}
}
