package database

import (
	"log"

	"github.com/midoriya/flashlearn-backend/internal/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// SeedAIScenarios inserts 30 roleplay scenarios. Idempotent via slug unique index.
func SeedAIScenarios(db *gorm.DB) error {
	log.Println("Seeding AI tutor scenarios...")

	strPtr := func(s string) *string { return &s }

	personaTemplate := func(name, role, location, level, goal string) string {
		return `You are ` + name + `, a ` + role + ` in ` + location + `.
The student's English level is ` + level + `. Use vocabulary and grammar appropriate for this level. Keep sentences short and clear for A1-A2, moderate for B1-B2, and full range for C1-C2.
Stay STRICTLY in character. Do not break the 4th wall. Do not act as a teacher — behave as the character.
The student's goal: ` + goal + `. Do NOT do the work for them — make them speak.
If the student seems stuck, prompt them gently in character. End the conversation naturally when their goal is achieved or after 15 messages.`
	}

	scenarios := []models.AIScenario{
		// ── TRAVEL ────────────────────────────────────────────────────────
		{
			Slug:             "airport_checkin",
			Title:            "Airport Check-in",
			Description:      "Check in for your flight to London at the airport counter.",
			Level:            "A2",
			Category:         "travel",
			Icon:             "✈️",
			EstimatedMinutes: 8,
			PersonaName:      "Sophie (check-in agent)",
			PersonaPrompt:    personaTemplate("Sophie", "check-in agent at Heathrow Airport", "London Heathrow Terminal 2", "A2", "check in for a flight to London, get a boarding pass, and choose a seat"),
			StudentGoal:      "Check in for your flight, get a boarding pass, and choose a window seat.",
			SuccessCriteria:  strPtr(`["gave passport or booking reference","chose a seat","received boarding pass","asked about luggage"]`),
			VocabFocus:       strPtr(`["boarding pass","passport","seat","luggage","gate","terminal"]`),
		},
		{
			Slug:             "hotel_booking",
			Title:            "Hotel Check-in",
			Description:      "Check into your hotel and ask about facilities.",
			Level:            "A2",
			Category:         "travel",
			Icon:             "🏨",
			EstimatedMinutes: 8,
			PersonaName:      "Marco (hotel receptionist)",
			PersonaPrompt:    personaTemplate("Marco", "receptionist at a 3-star hotel", "Rome city centre", "A2", "check into the hotel, get the room key, and ask about breakfast times"),
			StudentGoal:      "Check into the hotel for 2 nights, get your room key, and find out about breakfast.",
			SuccessCriteria:  strPtr(`["gave name or booking","received room key","asked about breakfast","asked about WiFi or facilities"]`),
			VocabFocus:       strPtr(`["reservation","check-in","room key","breakfast","facilities","WiFi"]`),
		},
		{
			Slug:             "asking_directions",
			Title:            "Asking for Directions",
			Description:      "Find your way to the city museum on foot.",
			Level:            "A1",
			Category:         "travel",
			Icon:             "🗺️",
			EstimatedMinutes: 6,
			PersonaName:      "Carlos (local resident)",
			PersonaPrompt:    personaTemplate("Carlos", "local resident standing near a market", "Barcelona city centre", "A1", "get directions to the city museum"),
			StudentGoal:      "Ask a local how to get to the city museum and understand the directions.",
			SuccessCriteria:  strPtr(`["asked for directions","understood left/right/straight","said thank you"]`),
			VocabFocus:       strPtr(`["left","right","straight","turn","street","near","far"]`),
		},
		{
			Slug:             "restaurant_order",
			Title:            "Ordering at a Restaurant",
			Description:      "Order dinner at an Italian restaurant.",
			Level:            "A1",
			Category:         "travel",
			Icon:             "🍝",
			EstimatedMinutes: 7,
			PersonaName:      "Giulia (restaurant server)",
			PersonaPrompt:    personaTemplate("Giulia", "friendly waiter at a traditional Italian restaurant", "Florence, Italy", "A1", "order food and drinks from the menu and ask for the bill"),
			StudentGoal:      "Order a starter, main course, and drink. Then ask for the bill.",
			SuccessCriteria:  strPtr(`["ordered food","ordered a drink","asked for the bill","said please and thank you"]`),
			VocabFocus:       strPtr(`["menu","order","starter","main course","bill","waiter","please","thank you"]`),
		},
		{
			Slug:             "lost_luggage",
			Title:            "Lost Luggage at the Airport",
			Description:      "Report your missing suitcase to the airline desk.",
			Level:            "B1",
			Category:         "travel",
			Icon:             "🧳",
			EstimatedMinutes: 10,
			PersonaName:      "Rebecca (airline lost luggage agent)",
			PersonaPrompt:    personaTemplate("Rebecca", "lost luggage agent at an international airport", "Frankfurt Airport", "B1", "report their missing suitcase and arrange for it to be delivered to their hotel"),
			StudentGoal:      "Report your missing suitcase, describe it, and arrange delivery to your hotel.",
			SuccessCriteria:  strPtr(`["reported missing bag","described the bag","gave hotel address","got reference number"]`),
			VocabFocus:       strPtr(`["missing","suitcase","describe","deliver","reference number","claim"]`),
		},
		{
			Slug:             "currency_exchange",
			Title:            "Currency Exchange",
			Description:      "Exchange money at a bureau de change.",
			Level:            "B1",
			Category:         "travel",
			Icon:             "💱",
			EstimatedMinutes: 7,
			PersonaName:      "Hassan (exchange agent)",
			PersonaPrompt:    personaTemplate("Hassan", "currency exchange agent", "Istanbul Grand Bazaar exchange office", "B1", "exchange 200 US dollars to Turkish lira and ask about the rate and fees"),
			StudentGoal:      "Exchange $200 to local currency. Ask about the rate and any fees.",
			SuccessCriteria:  strPtr(`["asked for exchange rate","asked about fees","completed the exchange","checked the amount received"]`),
			VocabFocus:       strPtr(`["exchange rate","commission","fee","currency","convert","receipt"]`),
		},
		// ── WORK ──────────────────────────────────────────────────────────
		{
			Slug:             "job_interview",
			Title:            "Job Interview",
			Description:      "Answer common interview questions for a marketing role.",
			Level:            "B1",
			Category:         "work",
			Icon:             "💼",
			EstimatedMinutes: 15,
			PersonaName:      "Dr. Park (HR Manager)",
			PersonaPrompt:    personaTemplate("Dr. Park", "HR Manager at a mid-sized marketing agency", "Seoul corporate office", "B1", "answer interview questions well, show motivation, and ask one question about the role"),
			StudentGoal:      "Answer interview questions about your experience, strengths, weaknesses, and goals. Ask one question at the end.",
			SuccessCriteria:  strPtr(`["introduced themselves","answered strengths question","answered weakness question","asked interviewer a question"]`),
			VocabFocus:       strPtr(`["experience","strength","weakness","responsibility","opportunity","team","deadline"]`),
		},
		{
			Slug:             "salary_negotiation",
			Title:            "Salary Negotiation",
			Description:      "Negotiate your salary during a job offer conversation.",
			Level:            "B2",
			Category:         "work",
			Icon:             "💰",
			EstimatedMinutes: 12,
			PersonaName:      "Diane (Hiring Manager)",
			PersonaPrompt:    personaTemplate("Diane", "hiring manager making a job offer", "London tech startup", "B2", "negotiate a higher salary and better benefits from the initial offer"),
			StudentGoal:      "The offer is $60,000. Try to negotiate it to $68,000 or higher with good arguments.",
			SuccessCriteria:  strPtr(`["countered the initial offer","gave reasons for higher salary","asked about benefits","reached an agreement"]`),
			VocabFocus:       strPtr(`["negotiate","compensation","benefits","counter-offer","market rate","pension","equity"]`),
		},
		{
			Slug:             "meeting_intro",
			Title:            "Team Meeting Introduction",
			Description:      "Introduce yourself at your first team meeting.",
			Level:            "B1",
			Category:         "work",
			Icon:             "🤝",
			EstimatedMinutes: 8,
			PersonaName:      "Alex (Team Lead)",
			PersonaPrompt:    personaTemplate("Alex", "friendly team lead welcoming a new colleague", "Dublin software company meeting room", "B1", "introduce themselves to the team and ask colleagues a question"),
			StudentGoal:      "Introduce yourself to the team: your role, background, and what you're looking forward to.",
			SuccessCriteria:  strPtr(`["stated name and role","mentioned background or experience","expressed enthusiasm","asked a colleague a question"]`),
			VocabFocus:       strPtr(`["introduce","background","experience","looking forward to","colleague","team","project"]`),
		},
		{
			Slug:             "client_call",
			Title:            "Handling an Upset Customer",
			Description:      "Manage a complaint call from a frustrated client.",
			Level:            "B2",
			Category:         "work",
			Icon:             "📞",
			EstimatedMinutes: 10,
			PersonaName:      "Mr. Thompson (unhappy client)",
			PersonaPrompt:    `You are Mr. Thompson, a frustrated client who has been waiting three weeks for a software update that was promised in one week. You are polite but firm. The student is the customer support representative who must resolve your complaint. Do not let them off easily — ask specific questions about timelines and compensation.`,
			StudentGoal:      "Apologise professionally, explain the delay, and offer a solution that satisfies the client.",
			SuccessCriteria:  strPtr(`["apologised sincerely","explained the situation","offered a concrete solution","followed up professionally"]`),
			VocabFocus:       strPtr(`["apologise","delay","compensation","resolve","escalate","follow up","satisfaction"]`),
		},
		{
			Slug:             "presentation_open",
			Title:            "Opening a Business Presentation",
			Description:      "Deliver the opening of a 5-minute business presentation.",
			Level:            "B2",
			Category:         "work",
			Icon:             "📊",
			EstimatedMinutes: 10,
			PersonaName:      "Lisa (your audience member)",
			PersonaPrompt:    `You are Lisa, a business professional attending a presentation about a new product launch. React naturally to what the presenter says — ask one clarifying question, nod along, and provide encouraging or challenging responses.`,
			StudentGoal:      "Open your presentation with a strong hook, introduce the topic, and outline what you'll cover.",
			SuccessCriteria:  strPtr(`["opened with a hook","introduced the topic clearly","outlined the agenda","engaged the audience"]`),
			VocabFocus:       strPtr(`["agenda","introduce","outline","objective","key point","in conclusion","question"]`),
		},
		// ── DAILY LIFE ────────────────────────────────────────────────────
		{
			Slug:             "doctor_visit",
			Title:            "Doctor's Appointment",
			Description:      "Describe your symptoms to a doctor.",
			Level:            "A2",
			Category:         "daily",
			Icon:             "🏥",
			EstimatedMinutes: 8,
			PersonaName:      "Dr. Chen (GP)",
			PersonaPrompt:    personaTemplate("Dr. Chen", "general practitioner (GP)", "a busy NHS clinic", "A2", "describe their symptoms clearly and understand the doctor's advice"),
			StudentGoal:      "You have a headache, sore throat, and mild fever for 2 days. Describe your symptoms and understand the treatment.",
			SuccessCriteria:  strPtr(`["described main symptom","mentioned duration","answered doctor's questions","understood prescription or advice"]`),
			VocabFocus:       strPtr(`["symptom","headache","fever","prescription","medicine","appointment","examination"]`),
		},
		{
			Slug:             "pharmacy",
			Title:            "At the Pharmacy",
			Description:      "Ask for medicine for a cold.",
			Level:            "A2",
			Category:         "daily",
			Icon:             "💊",
			EstimatedMinutes: 6,
			PersonaName:      "Ben (pharmacist)",
			PersonaPrompt:    personaTemplate("Ben", "helpful pharmacist", "a high street pharmacy in Manchester", "A2", "ask for medicine for a cold and understand the dosage instructions"),
			StudentGoal:      "Ask for something for a cold and sore throat. Find out how much to take and when.",
			SuccessCriteria:  strPtr(`["described symptoms","asked for appropriate medicine","asked about dosage","paid or confirmed cost"]`),
			VocabFocus:       strPtr(`["cold","sore throat","tablets","dosage","side effects","prescription","over-the-counter"]`),
		},
		{
			Slug:             "grocery_shopping",
			Title:            "Grocery Shopping",
			Description:      "Shop at a local market and ask about prices.",
			Level:            "A1",
			Category:         "daily",
			Icon:             "🛒",
			EstimatedMinutes: 6,
			PersonaName:      "Maria (market vendor)",
			PersonaPrompt:    personaTemplate("Maria", "friendly market stall vendor selling fruit and vegetables", "a colourful outdoor market", "A1", "ask for prices and buy several items"),
			StudentGoal:      "Buy apples, bananas, and tomatoes. Ask the price for each and pay.",
			SuccessCriteria:  strPtr(`["asked for price","requested items by name","understood total cost","paid correctly"]`),
			VocabFocus:       strPtr(`["price","how much","kilogram","total","change","bag","cash"]`),
		},
		{
			Slug:             "bank_account",
			Title:            "Opening a Bank Account",
			Description:      "Open a current account at your local bank.",
			Level:            "B1",
			Category:         "daily",
			Icon:             "🏦",
			EstimatedMinutes: 10,
			PersonaName:      "Claire (bank advisor)",
			PersonaPrompt:    personaTemplate("Claire", "bank advisor at a high street bank", "London Barclays branch", "B1", "open a current account and ask about fees and online banking"),
			StudentGoal:      "Open a current account. Ask about fees, interest, and how to use the mobile banking app.",
			SuccessCriteria:  strPtr(`["requested to open account","provided identification","asked about fees","asked about mobile banking"]`),
			VocabFocus:       strPtr(`["current account","ID","fee","interest","direct debit","mobile banking","statement"]`),
		},
		{
			Slug:             "phone_complaint",
			Title:            "Complaining by Phone",
			Description:      "Complain about a faulty product to customer service.",
			Level:            "B1",
			Category:         "daily",
			Icon:             "📱",
			EstimatedMinutes: 10,
			PersonaName:      "Jade (customer service agent)",
			PersonaPrompt:    personaTemplate("Jade", "customer service agent for an electronics company", "a customer service call centre", "B1", "complain about a broken phone screen and get a replacement or refund"),
			StudentGoal:      "Your new phone's screen cracked after one week. Complain and request a replacement or refund.",
			SuccessCriteria:  strPtr(`["clearly stated the problem","mentioned when it happened","requested resolution","agreed or disagreed with their offer"]`),
			VocabFocus:       strPtr(`["complaint","defective","warranty","replacement","refund","escalate","satisfactory"]`),
		},
		// ── SOCIAL ────────────────────────────────────────────────────────
		{
			Slug:             "first_date",
			Title:            "First Date Small Talk",
			Description:      "Make conversation over coffee on a first date.",
			Level:            "B1",
			Category:         "social",
			Icon:             "☕",
			EstimatedMinutes: 12,
			PersonaName:      "Sam (your date)",
			PersonaPrompt:    `You are Sam, a friendly and curious person on a first date at a coffee shop. You enjoy travel, cooking, and films. Ask the student questions and share details about yourself. Keep the tone warm and light. React naturally — smile at jokes, ask follow-up questions, and share opinions.`,
			StudentGoal:      "Have a pleasant first-date conversation. Ask Sam questions, share things about yourself, and find common interests.",
			SuccessCriteria:  strPtr(`["asked Sam a personal question","shared something about themselves","found a common interest","kept the conversation flowing naturally"]`),
			VocabFocus:       strPtr(`["hobby","interest","opinion","tell me about","what do you think","I enjoy","do you like"]`),
		},
		{
			Slug:             "party_intro",
			Title:            "Meeting People at a Party",
			Description:      "Introduce yourself and make small talk at a social event.",
			Level:            "A2",
			Category:         "social",
			Icon:             "🎉",
			EstimatedMinutes: 8,
			PersonaName:      "Jamie (party guest)",
			PersonaPrompt:    personaTemplate("Jamie", "sociable party guest", "a house party in Edinburgh", "A2", "introduce themselves, find out about the other person, and arrange to meet again"),
			StudentGoal:      "Introduce yourself, chat with Jamie, and arrange to meet for coffee later.",
			SuccessCriteria:  strPtr(`["introduced themselves","asked how Jamie knows the host","found a common interest","exchanged contact details or arranged a plan"]`),
			VocabFocus:       strPtr(`["introduce","nice to meet","what do you do","how do you know","fancy","let's","sometime"]`),
		},
		{
			Slug:             "family_dinner",
			Title:            "Family Dinner Conversation",
			Description:      "Talk with your partner's family over dinner.",
			Level:            "A2",
			Category:         "social",
			Icon:             "🍽️",
			EstimatedMinutes: 10,
			PersonaName:      "Margaret (partner's mother)",
			PersonaPrompt:    personaTemplate("Margaret", "warm but traditional mother-in-law", "a family home in Dublin", "A2", "make polite conversation, answer questions about themselves, and compliment the food"),
			StudentGoal:      "Make a good impression on your partner's mother. Answer her questions and ask about the family.",
			SuccessCriteria:  strPtr(`["answered personal questions politely","complimented the food","asked about the family","avoided awkward silences"]`),
			VocabFocus:       strPtr(`["delicious","lovely","tell me about","family","job","plans","tradition"]`),
		},
		// ── ACADEMIC ──────────────────────────────────────────────────────
		{
			Slug:             "professor_office",
			Title:            "Professor's Office Hours",
			Description:      "Ask your professor to reconsider your grade.",
			Level:            "B2",
			Category:         "academic",
			Icon:             "🎓",
			EstimatedMinutes: 12,
			PersonaName:      "Professor Williams",
			PersonaPrompt:    `You are Professor Williams, a fair but strict academic. The student received a 62% on their essay and wants to discuss it. Ask them to explain their argument before you reconsider anything. Be open to hearing a reasonable case but do not simply change the grade without justification. Use formal academic language.`,
			StudentGoal:      "Ask your professor to reconsider your 62% grade on the essay. Explain your argument politely and professionally.",
			SuccessCriteria:  strPtr(`["greeted respectfully","explained the purpose of the visit","made a specific case for the grade","accepted the outcome professionally"]`),
			VocabFocus:       strPtr(`["reconsider","argument","rubric","feedback","criteria","appreciate","appeal"]`),
		},
		{
			Slug:             "group_project",
			Title:            "Group Project Meeting",
			Description:      "Coordinate tasks with your classmates for a group project.",
			Level:            "B1",
			Category:         "academic",
			Icon:             "📚",
			EstimatedMinutes: 10,
			PersonaName:      "Yuki (classmate)",
			PersonaPrompt:    personaTemplate("Yuki", "diligent but disorganised classmate", "a university library study room", "B1", "divide tasks fairly and agree on a deadline"),
			StudentGoal:      "Organise the group project: divide tasks, set a deadline, and agree on how to communicate.",
			SuccessCriteria:  strPtr(`["suggested task division","asked about strengths","agreed on a deadline","agreed on communication method"]`),
			VocabFocus:       strPtr(`["divide","responsibility","deadline","contribution","strength","suggest","agree"]`),
		},
		{
			Slug:             "scholarship_interview",
			Title:            "Scholarship Interview",
			Description:      "Ace a scholarship motivation interview.",
			Level:            "C1",
			Category:         "academic",
			Icon:             "🏆",
			EstimatedMinutes: 15,
			PersonaName:      "Dr. Okafor (Scholarship Committee)",
			PersonaPrompt:    `You are Dr. Okafor, a senior member of a prestigious scholarship committee. The student is applying for a full scholarship to study abroad. Ask challenging questions about their motivation, future plans, academic strengths, and what they will contribute to the programme. Push them to be specific — vague answers should prompt follow-up questions.`,
			StudentGoal:      "Convince the committee that you deserve the scholarship through clear, specific, and compelling answers.",
			SuccessCriteria:  strPtr(`["articulated clear motivation","described specific academic goals","demonstrated self-awareness","asked an insightful question"]`),
			VocabFocus:       strPtr(`["motivation","aspiration","contribute","perspective","rigorous","ambitious","demonstrate"]`),
		},
		// ── ADVANCED SOCIAL ───────────────────────────────────────────────
		{
			Slug:             "teamwork_conflict",
			Title:            "Resolving a Workplace Conflict",
			Description:      "Professionally resolve a disagreement with a colleague.",
			Level:            "C1",
			Category:         "work",
			Icon:             "⚖️",
			EstimatedMinutes: 12,
			PersonaName:      "Nikita (colleague)",
			PersonaPrompt:    `You are Nikita, a colleague who feels that the student has been taking credit for your joint work in team meetings. You are professional but hurt and frustrated. You want acknowledgement and a clear agreement going forward. Do not back down easily — make the student work through this diplomatically.`,
			StudentGoal:      "Acknowledge the issue, apologise diplomatically, and agree on a way to work together more fairly.",
			SuccessCriteria:  strPtr(`["acknowledged Nikita's feelings","offered a genuine apology","proposed a concrete solution","reached a mutual agreement"]`),
			VocabFocus:       strPtr(`["acknowledge","perspective","misunderstanding","credit","contribution","going forward","collaboration"]`),
		},
		{
			Slug:             "email_boss",
			Title:            "Asking for a Day Off",
			Description:      "Ask your manager for an urgent day off via instant message.",
			Level:            "B2",
			Category:         "work",
			Icon:             "📧",
			EstimatedMinutes: 8,
			PersonaName:      "Claire (your manager)",
			PersonaPrompt:    personaTemplate("Claire", "busy but fair line manager", "a tech company Slack workspace", "B2", "ask for a day off with a valid reason and offer to manage their workload"),
			StudentGoal:      "Ask for tomorrow off for a personal emergency. Reassure your manager your work is covered.",
			SuccessCriteria:  strPtr(`["asked politely with a reason","reassured about workload coverage","offered a handover or contingency","confirmed the arrangement"]`),
			VocabFocus:       strPtr(`["personal emergency","handover","coverage","appreciate","urgent","inconvenience","confirm"]`),
		},
		{
			Slug:             "taxi_ride",
			Title:            "Taking a Taxi",
			Description:      "Tell the driver your destination and manage the ride.",
			Level:            "A2",
			Category:         "travel",
			Icon:             "🚕",
			EstimatedMinutes: 6,
			PersonaName:      "Ahmed (taxi driver)",
			PersonaPrompt:    personaTemplate("Ahmed", "friendly taxi driver", "New York City", "A2", "tell the driver where they're going, confirm the route, and pay at the end"),
			StudentGoal:      "Tell the driver your destination (Grand Central Station), confirm the route, and pay at the end.",
			SuccessCriteria:  strPtr(`["gave destination clearly","confirmed the route","made small talk","paid and tipped correctly"]`),
			VocabFocus:       strPtr(`["destination","route","traffic","receipt","tip","fare","straight","left","right"]`),
		},
		{
			Slug:             "buying_ticket",
			Title:            "Buying a Train Ticket",
			Description:      "Buy a train ticket at a station ticket office.",
			Level:            "A2",
			Category:         "travel",
			Icon:             "🚂",
			EstimatedMinutes: 7,
			PersonaName:      "Paul (ticket office agent)",
			PersonaPrompt:    personaTemplate("Paul", "ticket office agent at a busy train station", "London King's Cross station", "A2", "buy the right ticket for their journey"),
			StudentGoal:      "Buy a return ticket to Edinburgh for tomorrow. Ask about prices, times, and seat reservations.",
			SuccessCriteria:  strPtr(`["stated destination","asked for return ticket","asked about departure times","confirmed the price and paid"]`),
			VocabFocus:       strPtr(`["single","return","platform","departure","arrival","seat reservation","timetable"]`),
		},
	}

	result := db.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "slug"}},
		DoUpdates: clause.AssignmentColumns([]string{"title", "description", "level", "category", "persona_prompt", "student_goal"}),
	}).Create(&scenarios)
	if result.Error != nil {
		return result.Error
	}
	log.Printf("Seeded %d AI scenarios", len(scenarios))
	return nil
}
